# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
- devel
- release

env:
  global:
   - _R_CHECK_FORCE_SUGGESTS_=true

r_packages:
  - covr
  - devtools
  - roxygen2

# Do not build on these branches
branches:
  except:
    - decoders

after_success:
  - Rscript -e 'covr::codecov()'
