# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
  - devtools
  - roxygen2

# Do not build on these branches
branches:
  except:
    - decoders

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'install.packages("grattan", dep = TRUE)'
