source("./R/utils.R")

list(
  "E089" = list(long_name = "Initial_student_record_ind",
                orig_name = "E089",
                validate = function(v) is.integer(v) && all(v == 1L | v == 2L)),
  "E095" = list(long_name = "Student_course_combn_is_first",
                orig_name = "E095",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1, 2))),
  "E300" = list(long_name = "Record_type_cd",
                orig_name = "E300",
                mark_missing = never,
                validate = function(v) is.character(v) && all(v %fin% c("#", "$", "%", "1", "2", "3"))),
  "E306" = list(long_name = "HE_Provider_cd",
                orig_name = "E306",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(or(v == 0L,
                                                               between(v, 1000, 9999)))),
  "E306" = list(long_name = "HE_Provide_cd",
                orig_name = "E306",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(or(v == 0,
                                                               between(v, 1000, 9999)))),
  "E307" = list(long_name = "Course_cd",
                orig_name = "E307",
                mark_missing = never,
                validate = always),
  "E308" = list(long_name = "Course_name",
                orig_name = "E308",
                mark_missing = never,
                validate = always),
  "E310" = list(long_name = "Course_type",
                orig_name = "E310",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(v %in% c(1, 2, 12, 14, 3:7,
                                                                     11, 8:10, 13, 20:22,
                                                                     30, 41, 42, 50, 60,
                                                                     61, 80, 81, 82, 99))),
  "E312" = list(long_name = "Special_course",
                orig_name = "E312",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(v %in% c(0, 21:23, 25:27))),
  "E313" = list(long_name = "Student_id",
                orig_name = "E313",
                mark_missing = never,
                validate = always),
  "E314" = list(long_name = "DOB",
                orig_name = "E314",
                mark_missing = function(v) v == 19010101,
                validate = function(v) AND(is.integer(v) && all(between(v, 19010101, 20171231)),
                                           all(is.Date(v)))),
  "E315" = list(long_name = "Gender",
                orig_name = "E315",
                mark_missing = function(v) v == "X",
                validate = function(v) all(v %in% c("M", "F", "X"))),
  "E316" = list(long_name = "ATSI_cd",
                orig_name = "E316",
                mark_missing = function(v) v == 9,
                validate = function(v) is.integer(v) && all(v %in% c(2:5, 9))),
  "E319" = list(long_name = "Term_location",
                orig_name = "E319",
                mark_missing = function(v) substr(v, 2, 5) == "9999",
                validate = function(v) AND(is.character(v),
                                           all(or(substr(v, 2, 5) == "9999",
                                                  or(v %fin% paste0("X", 1200:9299),
                                                     between(as.integer(substr(v, 2, 5)), 1, 9998)))))),
  "E320" = list(long_name = "Home_location",
                orig_name = "E320",
                mark_missing = function(v) substr(v, 2, 5) == "9999",
                validate = function(v) AND(is.character(v),
                                           all(or(substr(v, 2, 5) == "9999",
                                                  or(v %fin% paste0("X", 1200:9299),
                                                     between(as.integer(substr(v, 2, 5)), 1, 9998)))))),




  "E327" = list(long_name = "New_admission_basis",
                orig_name = "E327",
                mark_missing = function(v) v == 99L,
                validate = function(v) is.integer(v) && all(v %in% c(1L, 31L, 33L, 34L, 36L, 37L, 29L, 99L))),
  "E328" = list(long_name = "Course_commencement_date",
                orig_name = "E328",
                mark_missing = never,
                validate = function(v) is.integer(v) && is.Date(v)),
  "E329" = list(long_name = "Mode_of_attendance",
                orig_name = "E329",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1, 5))),
  "E330" = list(long_name = "Attendance_type",
                orig_name = "E330",
                mark_missing = function(v) v == 9L,
                validate = function(v) is.integer(v) && all(v %in% c(0L, 1L, 2L, 9L))),
  "E333" = list(long_name = "Academic_org",
                orig_name = "E333",
                mark_missing = never,
                validate = always),
  "E335" = list(long_name = "Academic_org_unit_grp_cd",
                orig_name = "E335",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 1299))),
  "E337" = list(long_name = "Industry_work_experience",
                orig_name = "E337",
                mark_missing = never,
                validate = function(v) all(between(v, 0, 2))),
  "E339" = list(long_name = "EFTSL",
                orig_name = "E339",
                mark_missing = never,
                validate = function(v) is.double(v) && all(between(v, 0, 1))),
  "E346" = list(long_name = "Country_of_birth",
                orig_name = "E346",
                mark_missing = function(v) v >= 9998,
                validate = function(v) is.integer(v) && all(or(or(v == 1100L,
                                                                  between(v, 1200, 9299)),
                                                               or(v == 9998L,
                                                                  v == 9999L)))),
  "E347" = list(long_name = "Year_arrived_Aust",
                orig_name = "E347",
                mark_missing = function(v) substr(v, 1, 1) == "A",
                validate = function(v) is.character(v) && all(v %fin% c("0000",
                                                                        "0001",
                                                                        "1900",
                                                                        "2099",
                                                                        "A998",
                                                                        "A999"))),
  "E348" = list(long_name = "Language_home",
                orig_name = "E348",
                mark_missing = function(v) v >= 9998,
                validate = function(v) is.integer(v) && all(v %in% c(1L,
                                                                     seq.int(1000, 1199),
                                                                     seq.int(1300, 9799),
                                                                     8000L, # Indig
                                                                     9998L,
                                                                     9999L))),
  "E350" = list(long_name = "Course_of_study_load",
                orig_name = "E350",
                mark_missing = function(v) v == 0,
                validate = function(v) all(between(v, 0, 10))),
  "E354" = list(long_name = "Unit_of_study_cd",
                orig_name = "E354",
                mark_missing = never,
                validate = always),

  "E355" = list(long_name = "Unit_of_study_completion_status",
                orig_name = "E355",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1, 5))),
  "E358" = list(long_name = "CitizenResidentInd",
                orig_name = "E358",
                mark_missing = function(v) v == 9,
                validate = function(v) is.integer(v) && all(or(between(v, 1, 5),
                                                               v == 8 | v == 9))),
  "E369" = list(long_name = "TER",
                orig_name = "E369",
                mark_missing = function(v) v >= 998,
                validate = function(v) is.integer(v) && all(or(or(v == 1L,
                                                                  between(v, 30L, 100L)),
                                                               or(v == 998L,
                                                                  v == 999L)))),
  "E381" = list(long_name = "Amt_paid_upfront",
                orig_name = "E381",
                mark_missing = never,
                validate = function(v) is.double(v) && all(between(v, 0, 99999999))),
  "E384" = list(long_name = "Tot_amt_charged",
                orig_name = "E384",
                mark_missing = never,
                # Note: uses dollars not cents
                validate = function(v) is.double(v) && all(between(v, 0, 999999))),
  "E385" = list(long_name = "Tot_exemption_granted",
                orig_name = "E385",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 99))),
  "E386" = list(long_name = "Disability",
                orig_name = "E386",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v %% 10, 0, 2) &
                                                              between(nth_digit_of(v, 8), 0, 2) &
                                                              between(nth_digit_of(v, 7), 0, 1) &
                                                              between(nth_digit_of(v, 6), 0, 1) &
                                                              between(nth_digit_of(v, 5), 0, 1) &
                                                              between(nth_digit_of(v, 4), 0, 1) &
                                                              between(nth_digit_of(v, 3), 0, 1) &
                                                              between(nth_digit_of(v, 2), 0, 2))),
  "E390" = list(long_name = "Eligibility",
                orig_name = "E390",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 3))),
  "E392" = list(long_name = "Max_student_contr_ind",
                orig_name = "E392",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(v %in% c(0, 7, 5))),
  "E394" = list(long_name = "Course_of_study_name",
                orig_name = "E394",
                mark_missing = never,
                validate = always),
  "E402" = list(long_name = "Surname",
                orig_name = "E402",
                mark_missing = never,
                validate = always),
  "E403" = list(long_name = "Forename",
                orig_name = "E403",
                mark_missing = never,
                validate = always),
  "E404" = list(long_name = "Other_name",
                orig_name = "E404",
                mark_missing = never,
                validate = always),
  "E405" = list(long_name = "Name_title",
                orig_name = "E405",
                mark_missing = never,
                validate = always),
  "E406" = list(long_name = "Postal_address_1",
                orig_name = "E406",
                mark_missing = never,
                validate = always),
  "E407" = list(long_name = "Postal_address_2",
                orig_name = "E407",
                mark_missing = never,
                validate = always),
  "E406" = list(long_name = "Postal_address_1",
                orig_name = "E406",
                mark_missing = never,
                validate = always),
  "E408" = list(long_name = "Staff_classification_type",
                orig_name = "E408",
                mark_missing = function(v) v == 999,
                validate = function(v) is.integer(v) && all(v %in% c(1,
                                                                     5,
                                                                     13,
                                                                     14,
                                                                     42,
                                                                     66,
                                                                     100,
                                                                     200,
                                                                     220,
                                                                     seq.int(201, 210),
                                                                     999))),
  "E409" = list(long_name = "Postal_address_postcode",
                orig_name = "E409",
                mark_missing = function(v) if (is.integer(v)) v == 0L else v == "    ",
                validate = function(v) OR(is.integer(v) && all(between(v, 0, 9999)),
                                          all(between(as.integer(v), 0, 9999)))),
  "E412" = list(long_name = "Work_function_code",
                orig_name = "E412",
                mark_missing = function(v) v == 9,
                validate = function(v) is.integer(v) && all(v %in% c(1, 2, 3, 4, 9))),
  "E423" = list(long_name = "Current_salary",
                orig_name = "E423",
                mark_missing = function(v) v == 9,
                validate = function(v) is.integer(v) && all(between(v, 0, 800e3))),
  "E415" = list(long_name = "Reporting_yr",
                orig_name = "E415",
                mark_missing = never,
                validate = function(v) is.integer(v) && AND(all(between(v %% 10, 1, 2)),
                                                            all(between(v, 19891, 99992)))),
  "E446" = list(long_name = "Variation_reason_cd",
                orig_name = "E446",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1, 5))),
  "E455" = list(long_name = "Combined_course_study_ind",
                orig_name = "E455",
                mark_missing = never,
                validate = function(v) OR(is.logical(v),
                                          AND(is.integer(v),
                                              all(between(v, 0, 1))))),
  "E460" = list(long_name = "Prev_RTS_EFTSL",
                orig_name = "E460",
                mark_missing = never,
                validate = function(v) is.integer(v) && between(v, 0, 9999)),
  "E461" = list(long_name = "FOE_cd",
                orig_name = "E461",
                mark_missing = never,
                validate = function(v) all(or(v == 0,
                                              between(v, 10000, 129999)))),
  "E462" = list(long_name = "FOE_supp_cd",
                orig_name = "E462",
                mark_missing = never,
                validate = function(v) all(or(v == 0,
                                              between(v, 10000, 129999)))),
  "E463" = list(long_name = "Specialization_cd",
                orig_name = "E463",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 10000, 129999))),
  "E464" = list(long_name = "Discipline_cd",
                orig_name = "E464",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 10000, 129999))),

  "E465" = list(long_name = "Sep_status_High_Degree_Research",
                orig_name = "E465",
                mark_missing = never,
                validate = function(v) all(v %in% c(1, 2, 3, 9))),


  "E467" = list(long_name = "State_postal",
                orig_name = "E467",
                mark_missing = function(v) or(v == "   ", v == ""),
                validate = function(v) is.character(v) && all(trimws(v) %in% c("NSW",
                                                                               "VIC",
                                                                               "QLD",
                                                                               "WA",
                                                                               "SA",
                                                                               "TAS",
                                                                               "NT",
                                                                               "ACT",
                                                                               "AAT"))),
  "E470" = list(long_name = "State_residential",
                orig_name = "E470",
                mark_missing = function(v) or(v == "   ", v == ""),
                validate = function(v) is.character(v) && all(trimws(v) %in% c("NSW",
                                                                               "VIC",
                                                                               "QLD",
                                                                               "WA",
                                                                               "SA",
                                                                               "TAS",
                                                                               "NT",
                                                                               "ACT",
                                                                               "AAT"))),
  "E476" = list(long_name = "Commencing_location",
                orig_name = "E476",
                mark_missing = function(v) v == "99999",
                validate = function(v) is.character(v) && all(nchar(v) == 5L &
                                                                v %fin% c("00001",
                                                                          paste0("A", formatC(1:9998, width = 4, flag = "0")),
                                                                          "99999"))),
  "E477" = list(long_name = "Campus_postcode",
                orig_name = "E477",
                mark_missing = function(v) substr(v, 2, 5) == "9999",
                validate = function(v) is.character(v) && all(v %fin% c(paste0("X", c(1200:9299, 9999)),
                                                                        paste0("A", formatC(1:9998, width = 4, flag = "0")),
                                                                        "99999"))),
  "E486" = list(long_name = "Suburb",
                orig_name = "E486",
                mark_missing = never,
                validate = always),
  "E487" = list(long_name = "Scholarship_type_cd",
                orig_name = "E487",
                mark_missing = never,
                validate = function(v) is.integer(v) && v %in% c(0, 1, 2, 6, 7)),
  "E488" = list(long_name = "CHESSN",
                orig_name = "E488",
                mark_missing = never,
                validate = function(v) is.character(v)),
  "E489" = list(long_name = "Census_date",
                orig_name = "E489",
                mark_missing = never,
                validate = function(v) is.Date(v)),
  "E490" = list(long_name = "Student_status_cd",
                orig_name = "E490",
                mark_missing = never,
                validate = function(v) all(v %fin% paste0("E", fread("./data-raw/decoders/E490-decoders.txt")[["CODE"]]))),
  "E495" = list(long_name = "Indic_student_contr_amt",
                orig_name = "E495",
                mark_missing = function(v) v == 99999L,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999))),
  "E496" = list(long_name = "Indic_tuition_fee",
                orig_name = "E496",
                mark_missing = function(v) v == 99999L,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999))),
  "E497" = list(long_name = "Entry_cutoff_CSP",
                orig_name = "E497",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(between(v, 0, 9995))),
  "E498" = list(long_name = "Entry_cutoff_domestic",
                orig_name = "E498",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(between(v, 0, 9995))),
  "E500" = list(long_name = "Overseas_student_fee_",
                orig_name = "E500",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999))),

  "E521" = list(long_name = "OS_HELP_Study_period_start_date",
                orig_name = "E521",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v)),
  "E522" = list(long_name = "Cohort_year",
                orig_name = "E522",
                mark_missing = function(v) between(v, 0, 1),
                validate = function(v) is.integer(v) && or(between(v, 0, 1),
                                                           between(v, 2005, 2009))),
  "E523" = list(long_name = "Qld_entry_cut_off_CSP",
                orig_name = "E523",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v)),
  "E524" = list(long_name = "Qld_entry_cut_off_domestic",
                orig_name = "E524",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v)),
  "E527" = list(long_name = "HELP_debt_incurral_date",
                orig_name = "E527",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v)),
  "E528" = list(long_name = "OS_HELP_Payment_amt",
                orig_name = "E528",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999999))),
  "E529" = list(long_name = "Loan_fee",
                orig_name = "E529",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999999))),
  "E533" = list(long_name = "Course_of_study_cd",
                orig_name = "E533",
                mark_missing = function(v) if (is.numeric(v)) v == 0L else v == "0000000000",
                validate = function(v) TRUE),
  "E534" = list(long_name = "Course_of_study_start_date",
                orig_name = "E534",
                mark_missing = never,
                validate = function(v) is.integer(v) && is.YearMonth(v)),
  "E536" = list(long_name = "Course_fee_type",
                orig_name = "E536",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(v %in% seq.int(0, 3))),
  "E550" = list(long_name = "Ref_year",
                orig_name = "E550",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1987, 2099))),
  "E551" = list(long_name = "SummerWinter_school_ind",
                orig_name = "E551",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 1, 3))),
  "E558" = list(long_name = "HELP_debt_amt",
                orig_name = "E558",
                mark_missing = never,
                validate = function(v) is.integer(v) && all(between(v, 0, 99999999))),
  "E572" = list(long_name = "Year_left_school",
                orig_name = "E572",
                mark_missing = function(v) or(v == 0L,
                                              v == 1L,
                                              v >= 9997L),
                validate = function(v) is.integer(v) && all(between(v, 0, 9999))),
  "E573" = list(long_name = "Education_parent1",
                orig_name = "E573",
                mark_missing = function(v) v %in% c(1, 49, 98, 99),
                validate = function(v) is.integer(v) && all(v %in% c(20, 21, 22, 23, 24, 25, 26))),
  "E574" = list(long_name = "Education_parent2",
                orig_name = "E574",
                mark_missing = function(v) v %in% c(1, 49, 98, 99),
                validate = function(v) is.integer(v) && all(v %in% c(20, 21, 22, 23, 24, 25, 26))),
  "E578" = list(long_name = "Completion_percentage",
                orig_name = "E578",
                mark_missing = function(v) v == 100L,
                validate = function(v) is.integer(v) && all(between(v, 0, 100))),
  "E579" = list(long_name = "Joint_degree_partner_HE_Provider_cd",
                orig_name = "E579",
                mark_missing = function(v) v == 0L,
                validate = function(v) is.integer(v) && all(or(v == 0L,
                                                               between(v, 1000, 7997)))),
  "E582" = list(long_name = "OS_HELP_Language_studied",
                orig_name = "E582",
                mark_missing = function(v) v == 9999,
                validate = function(v) is.integer(v) && all(or(between(v, 1000, 9799),
                                                               v == 9999))),
  "E702" = list(long_name = "Aust_Yr12_result",
                orig_name = "E702",
                mark_missing = function(v) v == 10,
                validate = function(v) is.integer(v) && all(between(v, 1, 10))),
  "E710" = list(long_name = "IB_score",
                orig_name = "E710",
                mark_missing = function(v) v == 99,
                validate = function(v) is.integer(v) && all(or(between(v, 21, 45),
                                                               v == 99))),
  "E730" = list(long_name = "Prior_postgrad_course_year",
                orig_name = "E730",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 39999)))),

  "E731" = list(long_name = "Prior_degree",
                orig_name = "E731",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 39999)))),
  "E732" = list(long_name = "Prior_subdegree_course_HE",
                orig_name = "E732",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 39999)))),
  "E733" = list(long_name = "Prior_subdegree_course_VET",
                orig_name = "E733",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 39999)))),
  "E734" = list(long_name = "Prior_VET_award_course",
                orig_name = "E734",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 39999)))),
  "E735" = list(long_name = "Prior_secondary_edu_VET_course",
                orig_name = "E735",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 29999)))),
  "E736" = list(long_name = "Prior_secondary_edu_school_course",
                orig_name = "E736",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 29999)))),
  "E737" = list(long_name = "Prior_other_quals",
                orig_name = "E737",
                mark_missing = function(v) v == 10000 | v == 9999,
                validate = function(v) all(or(v %in% c(9999, 10000),
                                              between(v, 20000, 29999)))),
  "E913" = list(long_name = "Age_dv",
                orig_name = "E913",
                mark_missing = function(v) v == 0,
                validate = function(v) is.integer(v) && all(v == 0 | between(v, 12, 99))),

  "E919" = list(long_name = "State_permanent_home",
                orig_name = "E919",
                mark_missing = function(v) v == 9, # not idempotent
                validate = function(v) is.integer(v) && all(between(v, 0, 9), na.rm = TRUE)),
  "E920" = list(long_name = "State_permanent_home",
                orig_name = "E920",
                mark_missing = function(v) v == 9, # not idempotent
                validate = function(v) is.integer(v) && all(between(v, 0, 9), na.rm = TRUE)),
  "E922" = list(long_name = "Commencing_student_ind",
                orig_name = "E922",
                mark_missing = never,
                validate = function(v) OR(is.character(v) && all(v %in% c("1", "2")),
                                          is.integer(v) && all(between(v, 1L, 2L)))),
  "E996" = list(long_name = "State_of_institution",
                orig_name = "E996",
                mark_missing = never,
                validate = function(v) is.character(v) && all(trimws(v) %fin% c("NSW",
                                                                                "VIC",
                                                                                "QLD",
                                                                                "WA",
                                                                                "SA",
                                                                                "TAS",
                                                                                "NT",
                                                                                "ACT",
                                                                                "MUL",
                                                                                "OS"))),
  "E997" = list(long_name = "Participation_age",
                orig_name = "E997",
                mark_missing = function(v) v == 0,
                validate = function(v) is.integer(v) && all(v == 0 | between(v, 12, 99)))
) -> heims_data_dict

devtools::use_data(heims_data_dict, overwrite = TRUE)
